name: Node.js CI

on:
    push:
        branches: [master]
    pull_request:
        branches: [master]

jobs:
    build:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [14.x]

        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v2
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: "yarn"
            - run: yarn
            - run: yarn build
            - run: yarn export
            - run: yarn test -- --watchAll=false

            - name: Set Actions Allow Unsecure Commands
              run: |
                  echo "ACTIONS_ALLOW_UNSECURE_COMMANDS=true" >> $GITHUB_ENV

            - name: Deploy 🚀
              uses: JamesIves/github-pages-deploy-action@3.5.9
              with:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  BRANCH: gh-pages # The branch the action should deploy to.
                  FOLDER: out # The folder the action should deploy.
